import StyledComponentsRegistry from '@/lib/registry'
import './globals.css'
import { Inter } from 'next/font/google'
import ActiveHover from './menu'
import Styleddiv from './styleddiv'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Today's exercise",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const featuredPosts = ["home", "about", "contact"]
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <div>
            <Styleddiv>
              {featuredPosts.map((post, menu) => (
                  <div key={menu}>
                      <ActiveHover id={post}>
                          {post}
                      </ActiveHover>
                  </div>
              ))}
            </Styleddiv>
            {children}
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
